# Build settings

markdown_ext: mdxxx # 防止md文件被编译

paginate:     20   # 每页显示20条
paginate_path: /page/:num/
permalink:     ./post/:categories/:year-:month-:day-:title:output_ext

rss_path : ./feed.xml

source:  .
include: ["_kiss"]
exclude: ["node_modules", "scripts"]

destination:      ./.site
layouts_dir:      ./_layouts

excerpt_separator: <!--more-->  # you can specify your own separator, of course.
      
defaults:
  - scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "posts"
      comments: false
      category: "未归类"
